### PR TITLE
Update faraday

### LINKED ISSUE #6: faraday 0.13.0 support
Currently having an issue with the newer version of faraday since the run time restriction.
Using this in a chef cookbook, and another gem uses newer faraday. Not sure how much trouble it would be to up it, going to look more into it.

I have never worked with a making or working with ruby gems, so any help would be greatly appreciated.

Thanks for this wrapper its awesome.

### PR DESCRIPTION
**Pull request by cimnine**
Faraday version is controlled very tightly because breaking changes may be introduced with any minor version until Faraday reaches 1.0.0. This has was discussed in #5.

Fixes #6, #7

### CODE REVIEW

**Review by neckhair — APPROVED** [review]

**Comment by anthonyneto** [comment]
Yep that will fix my issue, however it will break again when faraday does another update. So just open another pull request?

Thanks

**Comment by chasebolt** [comment]
this is also an issue for us. having the version so tightly controlled is causing issues for us when chef updates its version of faraday. this gem ends up failing to install and then we are unable to make record changes to cloudflare.

**Comment by cimnine** [comment]
I completely understand the arguments of @chasebolt and @anthonyneto, but also the argument of @wa0x6e he made in #5.

After discussing this internally with my peers, we came to the conclusion that:

* We won't lock the upper version of faraday anymore.
* We add a notice to the `README.md` with lays out the situation with faraday.
* Anyone who wants to be more cautious may pin faraday to a version that suits him / her in his / her own `Gemfile`. An example has been added to the `README.md` file.
* We list versions of faraday, that are known to work, in the `README.md` file.

I hope this solution is a good enough compromise that embraces change while still offering a minimal compatibility guarantee.

**Comment by cimnine** [comment]
You'll find [`v0.2.0`](https://github.com/ninech/cloudflair/releases/tag/v0.2.0) on [rubygems.org](https://rubygems.org/gems/cloudflair/versions/0.2.0)

**Comment by chasebolt** [comment]
Great news. Thanks!

**Comment by greysteil** [comment]
I'm late to the party here, but would you guys be up for having an upper bound but automating its updating it, so you get a PR to bump it as soon as a new faraday version comes out?

I just added support for Ruby libraries to [Dependabot](https://dependabot.com) to do just that, based on [this blog post](https://blog.codeship.com/optimists-guide-pessimistic-library-versioning/) by Richard Schneeman. Here's an [example PR](https://github.com/greysteil/spot-gps/pull/7) it generated.

**Comment by chasebolt** [comment]
By doing that we become sole dependent on this gem updating before we can
update chef. Currently we have other gems that depend on faraday but don't
have this upper bounds limit. Relying on this gem to be updated before we
can update chef is something we are not crazy about.

**Comment by greysteil** [comment]
Fair enough!

**Comment by cimnine** [comment]
Out of curiosity: Which Chef module builds upon this Gem?

**Comment by chasebolt** [comment]
Chef bundles faraday. 

We have a custom chef cookbook/resource that uses the cloudflair gem to manage DNS records when a box is provisioned.

The issue that happened to us was that we don't pin minor versions for chef on a box provisioning. A new box spun up and installed a new minor version of chef - which included a version bump to faraday. Because of that version bump, the box failed to complete provisioning due to the cloudflair gem failing the version dependency check.

**Pull request merged**
